server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eco-service-users
    username: postgres
    password: Soksophorn
  jpa:
    show-sql: true